import type { Metadata } from "next";

import "./globals.css";
import Navbar from "@/components/Navbar";
import ContextProvider from "@/context/ContextProvider";
import { Bounce, ToastContainer } from "react-toastify";
import Footer from "@/components/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html lang="en" className={` h-full antialiased`}>
      <body className="min-h-full flex flex-col bg-[#0f1115]">
        <ContextProvider>
          <Navbar></Navbar>
          <main className="pt-20">{children}</main>
          <ToastContainer
            position="top-right"
            autoClose={1000}
            hideProgressBar={false}
            newestOnTop={false}
            closeOnClick
            rtl={false}
            pauseOnFocusLoss
            draggable
            pauseOnHover={false}
            theme="dark"
            transition={Bounce}
          />
          <Footer />
        </ContextProvider>
      </body>
    </html>
  );
}
