import type { Metadata } from "next";

import "./globals.css";
import Navbar from "@/components/Navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html lang="en" data-theme="light" className={` h-full antialiased`}>
      <body className="min-h-full flex flex-col">
        <Navbar></Navbar>
        <div>{children}</div>
      </body>
    </html>
  );
}
